#!/usr/bin/env python

import sys

import yaml

from mozawsdeploy import configure
from mozawsdeploy.puppet import create_node_yaml

fqdn = sys.argv[1]

configure(access_only=True)
print create_node_yaml(fqdn)
